apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odoo
spec:
  serviceName: "odoo"
  selector:
    matchLabels:
      app: odoo
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: "{{ .Values.odoo.image.name }}:{{ .Values.odoo.image.tag }}"
          imagePullPolicy: {{ .Values.odoo.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 8069
          env:
          - name: HOST
            value: "{{ .Values.odoo.postgresqlHost }}"
          - name: USER
            value: "{{ .Values.odoo.postgresqlUsername }}"
          - name: PASSWORD
            value: "{{ .Values.odoo.postgresqlPassword }}"
          volumeMounts:
          - name: config-volume
            mountPath: /etc/odoo
          - name: odoo-addons
            mountPath: /var/lib/odoo/addons/13.0
          - name: odoo-extra-addons
            mountPath: /mnt/extra-addons
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: odoo-config
            items:
            - key: config
              path: odoo.conf
  volumeClaimTemplates:
  - metadata:
      name: odoo-addons
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
  - metadata:
      name: odoo-extra-addons
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
