{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "odoo.fullname" . }}
spec:
  hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | squote }}
    {{- end }}    
  gateways:
    - {{ .Values.ingress.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8069
        host: odoo
{{- end }}
