# Default values for odoo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

odoo:
  service:
    type: ClusterIP
  image:
    name: odoo
    tag: 13.0
    pullPolicy: IfNotPresent
  postgresqlHost: odoo-postgresql
  postgresqlUsername: odoo
  postgresqlPassword: odoo

postgresql:
  postgresqlUsername: odoo
  postgresqlPassword: odoo
  postgresqlDatabase: postgres

ingress:
  enabled: true
  hosts:
    - host: "*"  
  gateway: "odoo-gateway"

istioLocal:
  enabled: true
